name: Push commit
on:
  push:
    branches: [ develop ]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit report
        run: |
          git config --global user.name 'Mario Guerrero'
          git config --global user.email 'marioe997@users.noreply.github.com'
          git commit -am "Automated report"
          git checkout "${GITHUB_REF:11}" 
          git push