name: Se corren los test y en caso de estar bien se realiza deploy hacia main
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]



jobs:
  build:
    name: 'Nodejs v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - 14
    steps:
       uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install mocha
        run: npm install -g mocha
      - name: Instalando Dependencias
        run: npm install
      - name: Ejecuta los test de nuestro proyecto
        run: npm run test